### ISSUE TITLE
Fibers issue?

### ISSUE THREAD

**Issue by nate-strauser** [raix/Meteor-rssfeed#5]
i'm getting this error in my logs

```
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/mnt/data/2/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/lampe:rssfeed/rss.server.js:100:1)
```

the feeds seem to work fine, so i'm thinking that the error is actually when the connect handler is passing the request on to other handlers

feed code is here https://github.com/nate-strauser/wework/blob/master/server/rss.js

feeds are running at:
http://www.weworkmeteor.com/rss/jobs
http://www.weworkmeteor.com/rss/experts

is this actually a problem with this package or something else in my code?  i'm not really sure.  everything seems to be working fine, so i'm not getting any good clues as to what the underlying issue is.

**Comment by raix** [comment]
odd - I cant see anything wrong with your code - the error seems to be thrown from the iron router package?

**Comment by nate-strauser** [comment]
yep - its coming from this line - https://github.com/iron-meteor/iron-router/blob/devel/lib/route_controller.js#L66

actually seems like its this issue - https://github.com/iron-meteor/iron-router/issues/1192 - closing this - sorry i just thought it might be rss related since the stack originated there, but it seems like iron router is the culprit with not wrapping with a bindenvironment

**Comment by raix** [comment]
super :)
